#!/bin/bash
# Zite: static website generator in one bash script!
# Usage:
# zite new my-website
# zite add articles my-article-name
# zite build
# 
# Don't forget to set the theme and name variables!

THEME="lazite" # configure theme
NAME="Zite Website" # website name
DATEFORMAT="+%Y-%m-%d" # used when creating new articles

if [ "$1" = "build" ]; then
  
  # reset the website directory
  if [ -d "website" ]; then
      rm -r "website"
  fi
  mkdir -p website/imgs website/styles website/fonts
  # copy styles, images, and fonts from theme
  for dir in "imgs" "styles" "fonts"; do
    if [ -d "themes/$THEME/$dir" ]; then
      cp -r "themes/$THEME/$dir"/* "website/$dir"
    fi
  done
  
  # read content categories and create html files with pandoc
  categories=($(ls content))
  for category in "${categories[@]}"; do
    title=$(tr '[:lower:]' '[:upper:]' <<< "$category")
    printf -- "---\ntitle: \"$title\"\n---\n\n" >> $category-temp.md
    if [ -d "content/$category/imgs" ]; then # if the imgs directory exists
      if [ -n "$(find "content/$category/imgs" -type f)" ]; then # and it's not empty
        cp content/$category/imgs/* website/imgs
      fi
    fi
    articles=($(ls -p content/$category/ | grep -v /))
    for article in "${articles[@]}"; do
      htmlname=$(basename $article | rev | cut -d"." -f2- | rev)
      printf -- "- [$(grep title content/$category/$article | sed 's/.*"\(.*\)".*/\1/')]($htmlname.html)\n\n" >> $category-temp.md
      sed -e 's/# /## /' content/$category/$article | pandoc --template=themes/$THEME/templates/page-template.html -o website/$htmlname.html
    done
    pandoc $category-temp.md --template=themes/$THEME/templates/list-template.html -o website/$category.html
    rm $category-temp.md
  done
  
  # creates home page
  printf -- "---\ntitle: \"$NAME\"\n---\n\n" >> home-temp.md
  for category in "${categories[@]}"; do
    title=$(tr '[:lower:]' '[:upper:]' <<< "$category")
    printf -- "- [$title]($category.html)\n" >> home-temp.md
  done
  pandoc home-temp.md --template=themes/$THEME/templates/home-template.html -o website/index.html
  rm home-temp.md
  
elif [ "$1" = "new" ]; then

  DIRNAME="$2" # directory name

  if [ ! -d "$DIRNAME" ]; then
    mkdir $DIRNAME $DIRNAME/content $DIRNAME/content/articles $DIRNAME/themes
  fi
  printf -- "---\ntitle:\"Welcome to Zite!\"\ndate: $(date $DATEFORMAT)\n---\n\n Welcome to Zite, the simple static website generator!\nCheck out the documentation [on the project's github page](github.com/rodrigueslazaro/zite)\n" > $DIRNAME/content/articles/intro.md

  printf "Congratulation, you've just created a Zite website!\n"

  if [ -z "$(ls -A $DIRNAME/themes)" ]; then
    printf "It appears you do not have a theme installed, please get the example theme from https://github.com/rodrigueslazaro/lazite-theme and place it inside the themes directory!\n"
  fi

elif [ "$1" = "add" ]; then

  CATNAME="$2" # category name
  NEWNAME="$3" # name of new md file
  NEWTITLE=$(sed -E 's/(^|[-_ ])([a-z])/\1\u\2/g; s/-/ /g' <<< $NEWNAME)
  
  printf -- "---\ntitle:\"$($NEWTITLE)\"\ndate: $(date $DATEFORMAT)\n---\n\n Welcome to Zite, the simple static website generator!\nCheck out the documentation [on the project's github page](github.com/rodrigueslazaro/zite)\n" > content/$CATNAME/$NEWNAME.md

fi

